server:
  port: 8081
spring:
  datasource:
    driverclassname: com.mysql.cj.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 0.0dzh
mybatis-plus:
  #信息输出设置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
